version: "3"

services:
    web:
        build: .
        image: checkdomain:3.x.x
        command: python3 /data/checkdomain/main.py
        volumes:
            - .:/data/checkdomain
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        networks:
            - checkdomainnet
        ports:
            - "127.0.0.1:6996:6996"
        restart: always

networks:
    checkdomainnet:
        external: true